// angular-webcomponents/src/app/app.component.ts
import { Component } from '@angular/core';
//import the custom components and register it with the browser. 
import './webcomponents/AutoCompleteTextInput';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  count: number = 0;
  suggestions: string[] = ['Advanced IT Project Management', 'Advanced Modeling', 'Advanced Software Testing', 'Führung von verteilten, multikulturellen und inernationalen Teams', 'Funktionale Programmierung', 'Requirements Engineering',
    'Softwarearchitektur', 'Software Engineering', 'User Centered Design', 'Advanced Software Quality Mangement', 'Software Frameworks'];
  placeholder = 'Enter subject...';
  selection: string;
  lostFocusWithoutInput: boolean = false;
  enteredValue: string;

  // called whenever lostFocus event was dispatched 
  handleLostFocus(event) {
    console.log("Received lost focus CustomEvent: " + event);
    const detail: string = event.detail;
    if (detail === undefined || detail.length == 0) {
      this.lostFocusWithoutInput = true;
      this.selection = null;
      return;
    }
    this.lostFocusWithoutInput = false;
    if (event.detail.length > 0) {
      this.enteredValue = event.detail;
    }
  }

  // called whenever chosenSubject event was dispatched 
  handleSelection(event) {
    console.log("Received chosenSubject CustomEvent: " + event);
    this.selection = event.detail;
  }
}
<div>
  <h1>Favourite subject:</h1>
  <auto-complete-text-input [placeholder]="placeholder" [suggestions]="suggestions" (lostFocus)="handleLostFocus($event)" (chosenSubject)="handleSelection($event)">
  </auto-complete-text-input>
</div>
<div *ngIf="lostFocusWithoutInput">You lost focus without providing any input.</div>
<div *ngIf="!lostFocusWithoutInput && enteredValue && !selection">You lost focus and entered: {{enteredValue}}</div>
<div *ngIf="selection !== 'Software Frameworks' && selection">
  <div>You selected {{selection}}, but actually you wanted to select Software Frameworks</div>
</div>
<div *ngIf="selection === 'Software Frameworks' && selection">
  You did the only right thing and selected {{selection}}
</div>
<router-outlet></router-outlet>

// react-webcomponents/src/App.js
import React, { Component } from 'react';
import { AutocompleteText } from './components/AutocompleteText.js';

class App extends Component {
    constructor(props) {
        super(props);

        this.state = {
            placeholder: 'Enter something...',
            suggestions: ['Advanced IT Project Management', 'Advanced Modeling', 'Advanced Software Testing', 'Führung von verteilten, multikulturellen und inernationalen Teams', 'Funktionale Programmierung', 'Requirements Engineering',
                'Softwarearchitektur', 'Software Engineering', 'User Centered Design', 'Advanced Software Quality Mangement', 'Software Frameworks']

        };
        // bind to this component
        this.handleLostFocus = this.handleLostFocus.bind(this);
        this.handleSelection = this.handleSelection.bind(this);
    }

    render() {
        return (
            <div>
                <h1>Autocomplete text input using Web Components</h1>
                <AutocompleteText placeholder={this.state.placeholder} suggestions={this.state.suggestions}
                    onLostFocus={this.handleLostFocus} onChosenSubject={this.handleSelection}></AutocompleteText>

                <p>{(this.state.lostFocus === '' && this.state.chosenSubject === '') ? 'You lost focus without providing any input.' : ''}</p>
                <p>{(this.state.lostFocus !== '' && this.state.chosenSubject === '') ? 'You lost focus and entered:' + this.state.lostFocus : ''}</p>
                <p>{(this.state.chosenSubject && this.state.chosenSubject !== 'Software Frameworks') ?
                    'You selected ' + this.state.chosenSubject + ', but actually you wanted to select Software Frameworks' : ''}</p>
                <p>{(this.state.chosenSubject && this.state.chosenSubject === 'Software Frameworks') ?
                    'You did the only right thing and selected ' + this.state.chosenSubject : ''}</p>
            </div>
        );
    }

    // called when custom lostFocus event was dispatched
    handleLostFocus(e) {
        this.setState({ lostFocus: e.detail, chosenSubject: ''});
    }

    // called when custom chosenSubject event was dispatched
    handleSelection(e) {
        this.setState({ chosenSubject: e.detail });
    }
}

export default App;
